#!/bin/bash 

appRoot=~/GitHub/bsteeleMusicApp
cd $appRoot
src=gs://songlyrics.bsteele.com
dst=songlyrics
json=$appRoot/src/main/webapp/allSongs.songlyrics

#rm -rf $dst
mkdir -p $dst
gsutil -m rsync -d $src/ $dst

cd $dst

rm -f $json
firstJson=1

IFS=$(echo -en "\n\b")
for f in *.songlyrics
do
	echo $f
	c=`head -1 "$f" `
	if [ ${c:0:1} == '<' ]; then
		#	convert an old style file to new
		lyricsToJson -i "$f"
		echo "	conversion"
	fi

	if [ "$firstJson" -eq 1 ]; then
		firstJson=0
		#echo "let newSongs = [" > $json
		echo "[" > $json
	else
		echo "," >> $json
	fi

	cat "$f" >> $json

done
echo "]" >> $json

#rm -rf $appRoot/$dst

exit 0
