#!/bin/tcsh
#set echo; set verbose

bsteeleMusicApp_buildId

mvn -e \
	-DgenerateJsInteropExports=true \
	-Dgwt.logLevel=INFO \
	-Dgwt.style=DETAILED  \
	-Dgwt.compiler.compileReport=false \
	-Ddeploy=true \
	clean tomcat7:redeploy		#	assumes it's already there, otherwise: deploy
