#!/bin/tcsh
#set echo; set verbose

bsteeleMusicApp_buildId

mvn \
	-DgenerateJsInteropExports=true \
	-Dgwt.logLevel=INFO \
	-Dgwt.style=DETAILED  \
	clean tomcat7:redeploy		#	assumes it's already there, otherwise: deploy
