#!/bin/bash 

#	asure we are in the correct place
appRoot=~/GitHub/bsteeleMusicApp
cd $appRoot

echo
date
pwd

src=gs://songlyrics.bsteele.com
dst=songlyrics
json=$appRoot/src/main/java/com/bsteele/bsteeleMusicApp/client/resources/allSongs.songlyrics

#	copy the google store images to local
mkdir -p $dst
#	note: without the -r option, gsutil rsync will not recurse into sub-directories, e.g. wars
gsutil -m rsync -p -d $src/ $dst

#	fail on \r in a file
od -c $dst/*.songlyrics | grep '\\r'
if [ $? -ne 1 ]; then
	exit $?    #	a \r found
fi


#	convert any ancient file formats
cd $dst
conversions=0
IFS=$'\n'
for f in *.songlyrics
do
	echo $f
	c=`head -1 "$f" `
	if [ ${c:0:1} == '<' ]; then
		#	convert an old style file to new
		lyricsToJson -i "$f"
		echo "	conversion"
		conversions=1
	fi

done

if [ "$conversions" -eq 1 ]; then
	#	put any modified files back to source
	cd $appRoot
	gsutil -m rsync -p $dst/ $src
fi


#	write the output file
cd $appRoot/$dst
rm -f $json

#	open the JSON
echo '[' > $json

#	copy and modify the contents
firstJson=1
IFS=$'\n'
for f in *.songlyrics
do
	echo "$f"
	if [ "$firstJson" -eq 1 ]; then
		firstJson=0
	else
		echo "," >> $json
	fi

	#	set the file and modification date
	echo '{ "file": "'$f'", "lastModifiedDate":' `stat -c %Y000.0 $f`', "song": ' >> $json
	#	copy the song
	cat $f >>  $json
	echo '}' >> $json
done

#	close the JSON
echo ']' >> $json

exit $status
