#!/bin/tcsh
set debug=0
set isBeta=1

while ( $#argv > 0 )
	switch ( $1 )
#	case '-beta':
#		set isBeta=1
#		shift
#		continue;
	case '-d':		#	debug
	case '-debug':
		set debug=1
		shift
		continue;
	default:
		echo unknown argument: $1
		exit -1;
		breaksw;
	endsw

	break;
end


if ( $debug != 0 ) then
	set echo; set verbose
endif

set dst=/var/www/html/public_html
if ( $isBeta != 0 ) then
	set dst=$dst/beta
endif
set git=~/GitHub/bsteeleMusicApp
set target=$git/target

set app=$git:t:r
set finalWar=$target/$app.war
echo deploy $app\: $finalWar to $dst

#	get the songlyrics from the cloud
$git/bsteeleMusicApp_lyrics_update

#	compile for deployment
set cwd=`pwd`
cd $git

mvn \ 
	-DgenerateJsInteropExports=false \
	-Dgwt.logLevel=SEVERE \
	-Dgwt.style=OBF  \
	-Dgwt.compiler.compileReport=false \
	-Ddeploy=true \
	clean install

rm -f $finalWar
#	expecting only one war file
set war=`find $git -iname "*.war" -print | tail -1 `

#	shrink and obfuscate the java classes
set tmp=`mktemp -d /tmp/bsteeleMusicApp_tmp.XXXXXXXXXX`
cd $tmp
jar -xf $war
java -jar /home/bob/my/installs/proguard/proguard/lib/proguard.jar @$git/bsteeleMusicApp_proguard \
	-injars WEB-INF/classes \
	-outjars WEB-INF/pgclasses.jar
if ( $status != 0 ) exit -1;
rm -rf WEB-INF/classes
jar -cfm $finalWar META-INF/MANIFEST.MF *
cd $cwd
rm -rf $tmp

#	generate app on localhost web
#	note: with github, it really doesn't need to be in google_drive
rm -rf $dst/$app	#	wow!
mkdir -p $dst/$app
cd $dst/$app
jar -xf $finalWar
cd $cwd

#	deploy on tomcat
cp $finalWar /opt/tomcat/webapps

#	deploy on web
set gs=gs://www.bsteele.com/beta/$app
gsutil -m rsync -d -R $dst/$app/ $gs 	#	source needs the /
gsutil -m -q acl -r ch -u AllUsers:R $gs


if ( $isBeta != 0 ) then
	echo test local version of $app at:
	echo	http://localhost/public_html/beta/$app
	echo	http://bsteele.com/beta/bsteeleMusicApp
else
	echo test local version of $app at:
	echo	http://localhost/public_html/$app
	echo	http://localhost:8082/bsteeleMusicApp
	echo ... and deploy with bsteele_upload
endif

exit 0
